name: Sync Fork and Create Release

on:
  schedule:
    - cron: '36 1 * * MON' # Scheduled to run at 1:36 AM on Mondays
  workflow_dispatch: # On button click

jobs:
  sync-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        if: ${{ steps.fork-sync.outcome == 'success' || steps.check-sync.outcome == 'success' }}
        run: npm install

      - name: Run semantic-release
        if: ${{ steps.fork-sync.outcome == 'success' || steps.check-sync.outcome == 'success' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Sync Fork
        id: fork-sync
        uses: tgymnich/fork-sync@v1.8
        with:
          owner: enthec
          base: main
          head: main
        continue-on-error: true
