name: Validate
on: [push, pull_request, workflow_dispatch]
jobs:
  validate_structure:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: run structure validator
        run: python3 .github/workflows/scripts/structure_validator.py

  validate_categories:
    runs-on: ubuntu-22.04
    needs: validate_structure
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: run category validator
        run: python3 .github/workflows/scripts/category_validator.py

  validate_groups:
    runs-on: ubuntu-22.04
    needs: validate_structure
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: run category validator
        run: python3 .github/workflows/scripts/group_validator.py

  tech_matrix_prep:
    needs: [validate_categories, validate_groups]
    uses: ./.github/workflows/tech_matrix_prep.yml

  validate_techs:
    runs-on: ubuntu-22.04
    needs: tech_matrix_prep
    strategy:
      max-parallel: 20
      matrix:
        file_name: ${{ fromJson(needs.tech_matrix_prep.outputs.technologies) }}
        python-version: [ "3.12" ]
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: run tech validator
        run: python3 -m pip install bs4 && python3 .github/workflows/scripts/technology_validator.py
        env:
          TECH_FILE_NAME: ${{ matrix.file_name }}

  validate_icon_path:
    runs-on: ubuntu-22.04
    needs: validate_techs
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: run category validator
        run: python3 .github/workflows/scripts/icon_path_validator.py
